In [1]:
import numpy as np
import torch

In [2]:
x = torch.tensor([-10., 20., -np.inf, np.nan, np.inf])

In [3]:
x

tensor([-10.,  20., -inf,  nan,  inf])

In [10]:
torch.where(
    torch.isnan(x),
    torch.tensor([0.,0.,0.,0.,0.]),
    torch.clamp(x, -15., 15.)
)

tensor([-10.,  15., -15.,   0.,  15.])

In [4]:
torch.clamp(x, -15., 15.)

tensor([-10.,  15., -15.,  nan,  15.])

In [8]:
0. * x

tensor([-0., 0., nan, nan, nan])